// Generated by tools/map-viewer/server.py. Edit the JSON layout through the viewer.
// IWZ-LOAD: dvar=iwz_noir_placement

checksum()
{
    return "2304615129";
}

markers()
{
    items = [];
    item = spawnstruct();
    item.id = "ref_south";
    item.preset = "calibration";
    item.origin = (832.000000, -2264.000000, 8.000000);
    item.normal = (0.000000, 0.000000, 1.000000);
    item.yaw = 0.000000;
    items[items.size] = item;
    item = spawnstruct();
    item.id = "ref_north";
    item.preset = "calibration";
    item.origin = (498.000000, 3816.000000, 136.000000);
    item.normal = (0.000000, 0.000000, 1.000000);
    item.yaw = 90.000000;
    items[items.size] = item;
    item = spawnstruct();
    item.id = "ref_lower";
    item.preset = "calibration";
    item.origin = (2199.950000, 63.622600, -132.000000);
    item.normal = (0.000000, 0.000000, 1.000000);
    item.yaw = 180.000000;
    items[items.size] = item;
    item = spawnstruct();
    item.id = "ref_west";
    item.preset = "calibration";
    item.origin = (-501.602000, 1022.500000, -5.631794);
    item.normal = (0.079744, -0.000003, 0.996815);
    item.yaw = 270.000000;
    items[items.size] = item;
    item = spawnstruct();
    item.id = "revive_south";
    item.preset = "quick_revive";
    item.origin = (960.000000, -2264.000000, 4.000000);
    item.normal = (0.000000, 0.000000, 1.000000);
    item.yaw = 90.000000;
    items[items.size] = item;
    item = spawnstruct();
    item.id = "emc_south";
    item.preset = "wall_buy";
    item.origin = (704.000000, -2264.000000, 8.000000);
    item.normal = (0.000000, 0.000000, 1.000000);
    item.yaw = 90.000000;
    items[items.size] = item;
    item = spawnstruct();
    item.id = "magic_wheel_1";
    item.preset = "magic_wheel";
    item.origin = (550.053640, -1928.362524, 8.000000);
    item.normal = (0.000000, 0.000000, 1.000000);
    item.yaw = 0.000000;
    items[items.size] = item;
    item = spawnstruct();
    item.id = "zombie_spawn_1";
    item.preset = "zombie_spawn";
    item.origin = (687.618152, -1665.075595, 4.000000);
    item.normal = (0.000000, 0.000000, 1.000000);
    item.yaw = 0.000000;
    items[items.size] = item;
    item = spawnstruct();
    item.id = "zombie_spawn_2";
    item.preset = "zombie_spawn";
    item.origin = (865.707071, -1676.302100, 4.000000);
    item.normal = (0.000000, 0.000000, 1.000000);
    item.yaw = 0.000000;
    items[items.size] = item;
    item = spawnstruct();
    item.id = "zombie_spawn_3";
    item.preset = "zombie_spawn";
    item.origin = (1023.872187, -1679.405537, 4.000000);
    item.normal = (0.000000, 0.000000, 1.000000);
    item.yaw = 0.000000;
    items[items.size] = item;
    item = spawnstruct();
    item.id = "power_1";
    item.preset = "power";
    item.origin = (1181.156853, -2071.612246, 4.000000);
    item.normal = (0.000000, 0.000000, 1.000000);
    item.yaw = 270.000000;
    items[items.size] = item;
    item = spawnstruct();
    item.id = "barricade_1";
    item.preset = "barricade";
    item.origin = (1117.284422, -1847.992399, 4.000000);
    item.normal = (0.000000, 0.000000, 1.000000);
    item.yaw = 0.000000;
    items[items.size] = item;
    item = spawnstruct();
    item.id = "player_spawn_south";
    item.preset = "player_spawn";
    item.origin = (832.000000, -2264.000000, 8.000000);
    item.normal = (0.000000, 0.000000, 1.000000);
    item.yaw = 90.000000;
    items[items.size] = item;
    return items;
}
