#pragma once

namespace zombies_hintstrings
{
	struct hint_override
	{
		const char* key;
		const char* value;
	};

	// Audited against CODIW-Source/localize.json and the CP interaction scripts.
	// Sentence case for actions/status; retain proper names, bindings and cost slots.
	// Perk slogans and multi-sentence instructions keep their authored punctuation.
	inline constexpr hint_override overrides[]
	{
		{"DIRECT_BOSS_FIGHT_ACTIVATION", "Hold [{+usereload,+activate}] to start the boss fight (Requires all players)"},
		{"COOP_INTERACTIONS_ARCADE_HELPER_CYCLE_MODE", "Cycle modes"},
		{"COOP_CRAFTABLES_CANNOT_PLACE", "Move to a valid location"},
		{"COOP_CRAFTABLES_PICKUP", "Hold ^3&&1^7 to pick up"},
		{"COOP_CRAFTABLES_PLACE", "Press ^3[{+attack}]^7 to place"},
		{"COOP_CRAFTABLES_PLACE_CANCELABLE", "Press ^3[{+attack}]^7 to place\nPress ^3[{+actionslot 3}] ^7 to cancel"},
		{"COOP_INTERACTIONS_ARCADE_HELPER_JUMP", "[{+gostand}] Fire / jump\n\n\n"},
		{"COOP_INTERACTIONS_ARCADE_HELPER_QUIT", "\n[{+stance}] Quit"},
		{"COOP_INTERACTIONS_ARCADE_HELPER_RESTART", "[{+usereload,+activate}] Restart"},
		{"COOP_INTERACTIONS_CANNOT_BUY", "You cannot buy this item"},
		{"COOP_INTERACTIONS_CANNOT_BUY_SELF_REVIVE", "No Up N' Atoms revives remaining"},
		{"COOP_INTERACTIONS_CARDS_ACTIVE", "Use your active Fate and Fortune cards first"},
		{"COOP_INTERACTIONS_CRYPTID_HELPER", "Press [{+attack}] to throw a ball"},
		{"COOP_INTERACTIONS_EQUIPMENT_FULL", "Equipment already full"},
		{"COOP_INTERACTIONS_EXPLO_MAX", "Explosives already full"},
		{"COOP_INTERACTIONS_FNF", "Hold [{+usereload,+activate}] to refill your Fate and Fortune deck (^3$&&1^7)"},
		{"COOP_INTERACTIONS_FNF_USED_2", "Hold [{+usereload,+activate}] to refill your Fate and Fortune deck (^3$10000^7)"},
		{"COOP_INTERACTIONS_FNF_WHILE_ACTIVE", "Hold [{+usereload,+activate}] to refill your Fate and Fortune deck (^3$&&1^7)\n\n^2Warning^7: This will deactivate your active cards"},
		{"COOP_INTERACTIONS_MUST_BE_STANDING", "Stand up to play"},
		{"COOP_INTERACTIONS_NEED_MONEY", "^1Not enough cash^7"},
		{"COOP_INTERACTIONS_NO_MORE_CARDS_OWNED", "No Fate and Fortune decks remaining"},
		{"COOP_INTERACTIONS_PURCHASE_AMMO", "Hold [{+usereload,+activate}] to purchase ammo for the ^3&&2^7\n(^2$&&1^7)"},
		{"COOP_INTERACTIONS_REQUIRES_POWER", "^1Requires power^7"},
		{"COOP_INTERACTIONS_UPGRADE_MAXED", "^3Your weapon is fully upgraded^7"},
		{"COOP_INTERACTIONS_USE_ALL_CARDS", "Use every card in your Fate and Fortune deck before refilling"},
		{"COOP_INTERACTIONS_ZZ_HELPER", "Shoot the target to move your zombie.\n\nBeat the pace zombie to win."},
		{"COOP_PERK_MACHINES_1500", "\"Get them up faster!\"\nHold [{+usereload,+activate}] to purchase ^2Up N' Atoms^7 (^3$1500^7)"},
		{"COOP_PERK_MACHINES_2500", "\"Got health? Have more!\"\nHold [{+usereload,+activate}] to purchase ^2Tuff Nuff^7 (^3$2500^7)"},
		{"COOP_PERK_MACHINES_PERK_SLOTS_FULL", "Perk slots already full"},
		{"COOP_PERK_MACHINES_REMOVE_PERK", "Hold [{+usereload,+activate}] to remove this perk"},
		{"COOP_PERK_MACHINES_SMACK", "\"Punch them in the face!\"\nHold [{+usereload,+activate}] to purchase ^2Slappy Taffy^7 (^3$2000^7)"},
		{"COOP_PERK_MACHINES_ZAP", "\"Shock them all when you reload!\"\nHold [{+usereload,+activate}] to purchase ^2Blue Bolts^7 (^3$1500^7)"},
		{"CP_FINAL_ACTIVATE_RITUAL_CIRCLE", "Hold [{+usereload,+activate}] to activate the ritual circle"},
		{"CP_FINAL_ACTIVATE_TALISMAN", "Hold [{+usereload,+activate}] to activate the talisman"},
		{"CP_FINAL_CONTAINMENT_CHAMBER", "Hold [{+usereload,+activate}] to trap a zombie in the Containment Chamber"},
		{"CP_FINAL_EXIT_AFTERLIFE", "Hold [{+usereload,+activate}] to exit the Afterlife Theater (Requires all players)"},
		{"CP_FINAL_FNF_MEPH", "Hold [{+usereload,+activate}] to refill your Fate and Fortune deck"},
		{"CP_FINAL_INSERT_DISK", "Press [{+usereload,+activate}] to insert the disk into slot &&1"},
		{"CP_FINAL_INTERACTIONS_ADD_BRIDGE_PIECE", "Hold [{+usereload,+activate}] to add a bridge piece"},
		{"CP_FINAL_INTERACTIONS_ADD_CHARGED_FUSE", "Press [{+usereload,+activate}] to install an alien fuse"},
		{"CP_FINAL_INTERACTIONS_FINISH_BRIDGE", "Hold [{+usereload,+activate}] to finish building the bridge"},
		{"CP_FINAL_INTERACTIONS_NEED_PIECES", "More parts needed to build the bridge"},
		{"CP_FINAL_INTERACTIONS_OPEN_AREA", "Hold [{+usereload,+activate}] to &&1"},
		{"CP_FINAL_INTERACTIONS_PICKUP_BRUTE_HELMET", "Hold [{+usereload,+activate}] to pick up the Spaceland Brute's helmet"},
		{"CP_FINAL_INTERACTIONS_SYSTEM_OFFLINE", "System offline"},
		{"CP_FINAL_INTERACTIONS_UPGRADE_WEAPON", "Hold [{+usereload,+activate}] to Pack-a-Punch your ^3&&1^7 (^2$&&2^7)"},
		{"CP_FINAL_PAP_UPGRADE", "Press [{+usereload,+activate}] to install the fuses in Pack-a-Punch"},
		{"CP_FINAL_PICKUP_ITEM", "Hold [{+usereload,+activate}] to pick up this item"},
		{"CP_FINAL_PLACE_TALISMAN", "Hold [{+usereload,+activate}] to place the talisman"},
		{"CP_FINAL_SKULL_DEPLOY", "Hold [{+attack}] to entangle a block. Release [{+attack}] to launch it at a skull and form a combo.\n\n\n"},
		{"CP_FINAL_SUPER_USER", "Hold [{+usereload,+activate}] to override the access controls"},
		{"CP_FINAL_TIME_PERIOD", "Hold [{+usereload,+activate}] to change the time period"},
		{"CP_FINAL_TRAP_GENERIC", "Hold [{+usereload,+activate}] to activate the trap (^3$750^7)"},
		{"CP_FINAL_UPGRADE_WEAPON", "Hold [{+usereload,+activate}] to Pack-a-Punch your ^3&&1^7 (^2$&&2^7)"},
		{"CP_FINAL_VENOMX_AMMO", "Hold [{+usereload,+activate}] to add Venom-X ammo"},
		{"CP_TOWN_INTERACTIONS_ACTIVATE_FASTTRAVEL", "Hold [{+usereload,+activate}] to connect the teleportation device"},
		{"CP_TOWN_INTERACTIONS_ACTIVATE_TELEPORT", "Hold [{+usereload,+activate}] to start the teleportation sequence (Requires all players)"},
		{"CP_TOWN_INTERACTIONS_ADD_BLUEPRINT", "Press [{+usereload,+activate}] to add a blueprint to this station"},
		{"CP_TOWN_INTERACTIONS_ADD_COMPONENT", "Press [{+usereload,+activate}] to add a component"},
		{"CP_TOWN_INTERACTIONS_ADD_PART", "Hold [{+usereload,+activate}] to add a part"},
		{"CP_TOWN_INTERACTIONS_ATM_INSUFFICIENT_FUNDS", "Not enough cash in the ATM"},
		{"CP_TOWN_INTERACTIONS_ATM_WITHDRAWAL", "Hold [{+usereload,+activate}] to withdraw ^2$1000^7\nBalance: (^6$&&1^7)"},
		{"CP_TOWN_INTERACTIONS_BUY_WEAPON", "Hold [{+usereload,+activate}] to purchase the ^3&&1^7\n(^2$&&2^7)"},
		{"CP_TOWN_INTERACTIONS_ENTER_PORTAL", "Hold [{+usereload,+activate}] to activate the portal"},
		{"CP_TOWN_INTERACTIONS_FASTTRAVEL_INACTIVE", "Activate all teleportation devices first"},
		{"CP_TOWN_INTERACTIONS_HIDDEN_LEAVE", "Hold [{+usereload,+activate}] to return to the film"},
		{"CP_TOWN_INTERACTIONS_HIDDEN_TELEPORT", "Hold [{+usereload,+activate}] to access the Projection Room"},
		{"CP_TOWN_INTERACTIONS_JUKEBOX_OFF", "Hold [{+usereload,+activate}] to turn off the jukebox"},
		{"CP_TOWN_INTERACTIONS_JUKEBOX_ON", "Hold [{+usereload,+activate}] to turn on the jukebox"},
		{"CP_TOWN_INTERACTIONS_MACHINE_OUT_OF_ORDER", "This machine is out of order"},
		{"CP_TOWN_INTERACTIONS_PICKUP_CRANK", "Hold [{+usereload,+activate}] to add the crank"},
		{"CP_TOWN_INTERACTIONS_PICKUP_GRIP", "Hold [{+usereload,+activate}] to add the grip"},
		{"CP_TOWN_INTERACTIONS_PICKUP_HANDLE", "Hold [{+usereload,+activate}] to pick up the power handle"},
		{"CP_TOWN_INTERACTIONS_PICKUP_PLUNGER", "Hold [{+usereload,+activate}] to add the plunger"},
		{"CP_TOWN_INTERACTIONS_PLACE_BOMB_PIECE", "Hold [{+usereload,+activate}] to attach the part to the bomb"},
		{"CP_TOWN_INTERACTIONS_PUSH_BOMB", "Hold [{+usereload,+activate}] to push the bomb"},
		{"CP_TOWN_INTERACTIONS_START_REACTION", "Hold [{+usereload,+activate}] to start the reaction"},
		{"CP_TOWN_INTERACTIONS_TELEPORT_READY", "Hold [{+usereload,+activate}] to teleport the bomb (Requires all players)"},
		{"CP_TOWN_INTERACTIONS_UPGRADE_WEAPON", "Hold [{+usereload,+activate}] to Pack-a-Punch your ^3&&1^7 (^2$&&2^7)"},
		{"CP_TOWN_INTERACTIONS_UPGRADE_WEAPON_GENERIC", "Hold [{+usereload,+activate}] to Pack-a-Punch your weapon (^2$&&2^7)"},
		{"CP_TOWN_INTERACTIONS_USE_ELVIRA_TRAP", "Hold [{+usereload,+activate}] to activate the station defenses (^3$750^7)"},
		{"CP_TOWN_INTERACTIONS_VEHICLE_TELEPORT_READY", "Hold [{+usereload,+activate}] to teleport to the bomb (Requires all players)"},
		{"CP_ZOMBIE_AFTERLIFE_ARCADE_CANNOT_SPECTATE", "No teammates to spectate"},
		{"CP_ZMB_GHOST_KILL_GHOST", "Hold [{+attack}] to entangle a ghost. Release [{+attack}] to launch it at the skulls."},
		{"CP_ZMB_GHOST_SKULL_DEPLOY", "Hold [{+attack}] to entangle a block. Release [{+attack}] to launch it at a question block to match colors."},
		{"CP_ZOMBIE_AFTERLIFE_ARCADE_SELFREVIVE_DOOR", "Hold [{+usereload,+activate}] to revive yourself"},
		{"ZM_CONSUMABLES_BUTTON_KEYS", "Press [{+smoke}]+[{+frag}] to activate"},
		{"ZM_CONSUMABLES_BUTTON_KEYS_PC", "Press [{+special}] to activate"},
		{"ZM_CONSUMABLES_READY", "Press [{+actionslot 1}] to select"},
		{"ZM_TUTORIALS_TURN_ON_TUTORIALS", "Hold [{+usereload,+activate}] for a guided tour"},
		{"ZOMBIE_LOST_AND_FOUND_COLLECT_1", "Hold [{+usereload,+activate}] to claim your &&1 from the Lost and Found (^3$2000^7)"},
		{"ZOMBIE_LOST_AND_FOUND_NO_ITEM", "You have no items at the Lost & Found"},
		{"ZOMBIE_LOST_AND_FOUND_COLLECT_1_SOLO", "Hold [{+usereload,+activate}] to claim your &&1 from the Lost and Found"},
		{"ZOMBIE_LOST_AND_FOUND_COLLECT_2", "Hold [{+usereload,+activate}] to claim your &&1 and &&2 from the Lost and Found (^3$2000^7)"},
		{"ZOMBIE_LOST_AND_FOUND_COLLECT_2_SOLO", "Hold [{+usereload,+activate}] to claim your &&1 and &&2 from the Lost and Found"},
		// These failure conditions are verified in the map scripts; they have no
		// binding, name or price parameters despite gaps in the localization dump.
		{"CP_ZMB_INTERACTIONS_ATM_INSUFFICIENT_FUNDS", "Not enough cash in the ATM"},
		{"CP_RAVE_ATM_INSUFFICIENT_FUNDS", "Not enough cash in the ATM"},
		{"CP_DISCO_INTERACTIONS_ATM_INSUFFICIENT_FUNDS", "Not enough cash in the ATM"},
		{"CP_ZMB_INTERACTIONS_UPGRADE_WEAPON_FAIL", "Cannot upgrade this weapon"},
		{"CP_RAVE_UPGRADE_WEAPON_FAIL", "Cannot upgrade this weapon"},
		{"CP_DISCO_UPGRADE_WEAPON_FAIL", "Cannot upgrade this weapon"},
		{"CP_TOWN_UPGRADE_WEAPON_FAIL", "Cannot upgrade this weapon"},
		{"CP_FINAL_UPGRADE_WEAPON_FAIL", "Cannot upgrade this weapon"},
		{"CP_FINAL_INTERACTIONS_UPGRADE_WEAPON_FAIL", "Cannot upgrade this weapon"},
		{"CP_RAVE_WALL_BUY_DISABLED", "Weapon purchases are unavailable"},
		{"CP_RAVE_NEED_OFFERING", "You need an offering"},
		{"CP_RAVE_NEED_POUCH", "You need a pouch to enter Rave mode"},
		{"CP_ZMB_INTERACTIONS_MACHINE_OUT_OF_ORDER", "This machine is out of order"},
	};

	std::optional<std::string> normalize(std::string_view key, std::string_view value);
}
